In [1]:
import pandas as pd
df2=pd.read_csv("C:/Users/Sathyanarayanan/Downloads/airlines_flights_data.csv")
df2

,index,airline,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [2]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             300153 non-null  int64
 1   airline           300153 non-null  object
 2   source_city       300153 non-null  object
 3   departure_time    300153 non-null  object
 4   stops             300153 non-null  object
 5   arrival_time      300153 non-null  object
 6   destination_city  300153 non-null  object
 7   class             300153 non-null  object
 8   duration          300153 non-null  float64
 9   days_left         300153 non-null  int64
 10  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(7)
memory usage: 25.2+ MB

In [3]:
df2["airline"].unique()

array(['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo',
       'Air_India'], dtype=object)

In [4]:
df2["source_city"].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

In [5]:
df2["airline"].nunique()

6

In [6]:
df2["source_city"].nunique()

6

In [7]:
df2["destination_city"].unique()

array(['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi'],
      dtype=object)

In [8]:
df2["class"].unique()

array(['Economy', 'Business'], dtype=object)

In [9]:
df2["arrival_time"].unique()

array(['Night', 'Morning', 'Early_Morning', 'Afternoon', 'Evening',
       'Late_Night'], dtype=object)

In [10]:
df2["departure_time"].unique()

array(['Evening', 'Early_Morning', 'Morning', 'Afternoon', 'Night',
       'Late_Night'], dtype=object)

In [11]:
data2=df2[["index","days_left","price"]]
data2.corr()

              index  days_left     price
index      1.000000   0.014638  0.761177
days_left  0.014638   1.000000 -0.091949
price      0.761177  -0.091949  1.000000

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             300153 non-null  int64
 1   airline           300153 non-null  object
 2   source_city       300153 non-null  object
 3   departure_time    300153 non-null  object
 4   stops             300153 non-null  object
 5   arrival_time      300153 non-null  object
 6   destination_city  300153 non-null  object
 7   class             300153 non-null  object
 8   duration          300153 non-null  float64
 9   days_left         300153 non-null  int64
 10  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(7)
memory usage: 25.2+ MB

In [13]:
import pandas as pd
import scipy.stats as stats

df2['class'] = df2['class'].astype('category')

Economy = df2[df2['class'] == 'Economy']['price']
Business = df2[df2['class'] == 'Business']['price']

ttest_result = stats.ttest_ind(Economy, Business)

print(f"T-statistic: {ttest_result.statistic}")
print(f"P-value: {ttest_result.pvalue}")

if ttest_result.pvalue < 0.05:
    print("There is a significant difference in price between Economy and Business class")
else:
    print("There is no significant difference in price between Economy and Business class")

T-statistic: -1480.683826786644
P-value: 0.0
There is a significant difference in price between Economy and Business class

In [14]:
import pandas as pd
import scipy.stats as stats

df2['airline'] = df2['airline'].astype('category')

SpiceJet = df2[df2['airline'] == 'SpiceJet']['price']
AirAsia = df2[df2['airline'] == 'AirAsia']['price']
Vistara = df2[df2['airline'] == 'Vistara']['price']
GO_FIRST = df2[df2['airline'] == 'GO_FIRST']['price']
Indigo = df2[df2['airline'] == 'Indigo']['price']
Air_India = df2[df2['airline'] == 'Air_India']['price']

anova_result = stats.f_oneway(SpiceJet, AirAsia, Vistara, GO_FIRST, Indigo, Air_India)

print(f"F-statistic: {anova_result.statistic}")
print(f"P-value: {anova_result.pvalue}")

if anova_result.pvalue < 0.05:
    print("There is a  difference in price between airline.")
else:
    print("There is no significant difference in price between airline")

F-statistic: 17194.402096092348
P-value: 0.0
There is a  difference in price between airline.

In [15]:
import pandas as pd
from scipy.stats import chi2_contingency

table = pd.crosstab(df2['airline'], df2['class'])


chi2_stat, p_val, dof, expected = chi2_contingency(table)
print( chi2_stat)
print(p_val)

if p_val < 0.05:
    print("There is difference between airline and class")  # there is relationship
else:
    print("There is no difference between airline and class") # there is no relationship

60492.80487209428
0.0
There is difference between airline and class